Repository codelicia/xulieta, pull requests merged in 2020-11, with the labels that each got.

#40 Add workflow for automatic releases
  .github/workflows/release-on-milestone-closed.yml
Labels: enhancement

#42 Update psalm to 4.1.1
  composer.json
  src/Command/App.php
Labels: enhancement

#41 Fix location of the xml namespace schema
  README.md
Labels: documentation

#45 Fix issue with php short tag #44
  src/Lint/PhpLint.php
  tests/assets/understand-short-tag.md
  tests/assets/understand-short-tag.rst
  tests/functional/md-short-php-tag.phpt
  tests/functional/rst-short-php-tag.phpt
Labels: bug, enhancement

#48 Create new milestone after a release
  .github/workflows/release-on-milestone-closed.yml
Labels: bug

#50 README: format and add badges
  README.md
Labels: documentation, enhancement

#49 Remove ignored file from psalm.xml
  psalm.xml
Labels: enhancement

#51 Make Plugin easier to implement
  composer.json
  psalm.xml
  src/Command/App.php
  src/Config/ConfigFileValidation.php
  src/Lint/Lint.php
  src/Parser/MarkdownParser.php
  src/Parser/MultipleParser.php
  src/Parser/Parser.php
  src/Parser/RstParser.php
  src/Plugin/MultiplePlugin.php
  src/Plugin/PhpOnMarkdownPlugin.php
  src/Plugin/PhpOnRstPlugin.php
  src/Plugin/Plugin.php
  src/Validator/MultipleValidator.php
  src/Validator/PhpValidator.php
  src/Validator/Validator.php
  tests/assets/invalid-file.rst
  tests/functional/rst-invalid-file.phpt
  tests/unit/Parser/MarkdownParserTest.php
  tests/unit/Validator/PhpValidatorTest.php
  xulieta.xsd
Labels: enhancement

#52 Add more information when asking for verbose output
  src/Command/App.php
  tests/functional/verbose.phpt
Labels: enhancement

#55 Improve standard output format
  src/Output/Stdout.php
  tests/functional/md-immediately-php-open-tag.phpt
  tests/functional/md-syntax-error.phpt
  tests/functional/rst-immediately-php-open-tag.phpt
  tests/functional/rst-syntax-error.phpt
Labels: enhancement

#57 Improve standard output format
  src/Output/Stdout.php
  tests/functional/md-immediately-php-open-tag.phpt
  tests/functional/md-syntax-error.phpt
  tests/functional/rst-immediately-php-open-tag.phpt
  tests/functional/rst-syntax-error.phpt
Labels: enhancement

#60 Fix configuration to allow single plugins
  src/Command/App.php
  src/Config/ConfigFileValidation.php
Labels: bug

#62 Fix bug with unsupported language code sample [0.1.x]
  tests/assets/unsupported-language.md
  tests/functional/unsupported-language.phpt
Labels: bug, enhancement

#63 Fix bug with unsupported language code sample [0.2.x]
  tests/assets/unsupported-language.md
  tests/functional/unsupported-language.phpt
Labels: bug, enhancement
